version: "3"

services:
  asterisk:
    build: .
    container_name: asterisk-dongle
    privileged: true
    restart: always
    network_mode: host
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - ./configs:/etc/asterisk
      - ./data:/var/spool/asterisk
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyUSB1:/dev/ttyUSB1
      - /dev/ttyUSB2:/dev/ttyUSB2
