[general]
static=yes
writeprotect=no

[default]
exten => 1000,1,Answer()
 same => n,Dial(SIP/ramal1000)
 same => n,Hangup()

[incoming]
exten => s,1,Answer()
 same => n,Playback(hello-world)
 same => n,Hangup()
